In [1]:
import pandas as pd

In [2]:
from scipy.spatial.distance import canberra

In [5]:
!pip install haversine

Requirement already satisfied: haversine in c:\users\mmehak\appdata\local\anaconda3\lib\site-packages (2.9.0)

In [3]:
import haversine.haversine

In [4]:
df=pd.read_csv("I:/dep_coupland/grp_fulgione/common/1000Genomes/SampleList_SpanishProject/CAN.poplabels", sep=" ", header= None)

In [5]:
df

       0     1    2  3
0      1  ES01  CAN  1
1     97  ES01  CAN  1
2     35  ES01  CAN  1
3     62  ES01  CAN  1
4     44  ES01  CAN  1
..   ...   ...  ... ..
206  804  ES25  CAN  1
207  805  ES25  CAN  1
208  806  ES25  CAN  1
209  807  ES25  CAN  1
210  808  ES25  CAN  1

[211 rows x 4 columns]

In [6]:
set1=set(df[0].astype(str))

In [56]:
env=pd.read_csv("ClimateData.csv")

In [57]:
env

,Plant ID,Latitude,Longitude,bio_1_Annual_Mean_Temperature,bio_2_Mean_Diurnal_Range,bio_3_Isothermality,bio_4_Temperature_Seasonality,bio_5_Max_Temperature_of_Warmest_Month,bio_6_Min_Temperature_of_Coldest_Month,bio_7_Temperature_Annual_Range,...,wind_Apr,wind_May,wind_Jun,wind_Jul,wind_Aug,wind_Sep,wind_Oct,wind_Nov,wind_Dec,Elev
0,ES01-001-C-00,42.993168,-5.910047,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,24.600000,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
1,ES01-004-C-00,42.993525,-5.910298,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,24.600000,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
2,ES01-005-C-00,42.992989,-5.909456,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,24.600000,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
3,ES01-007-C-00,42.993225,-5.910316,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,24.600000,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
4,ES01-008-S-00,42.993150,-5.910366,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,24.600000,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,ES25-005-S-01,43.153210,-3.569940,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,22.199999,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168
207,ES25-006-S-01,43.153210,-3.569940,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,22.199999,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168
208,ES25-007-S-01,43.153210,-3.569940,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,22.199999,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168
209,ES25-008-S-01,43.153210,-3.569940,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,22.199999,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168
210,ES25-009-S-01,43.153210,-3.569940,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,22.199999,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168

In [64]:
names_info=pd.read_csv("I:/dep_coupland/grp_fulgione/common/1000Genomes/SampleList_SpanishProject/1000Genomes_final_Cantabrians.txt", header= None,sep="\t")

In [65]:
names_info

,0,1,2,3,4,5,6,7,8
0,1,E1-20-08-01,E1,ES01-001-C-01,ES01-001-C-00,ES01,IBE,-,-
1,97,E1-20-08-08-1,E1,ES01-001-S-00-W,ES01-001-S-00-W,ES01,IBE,-,-
2,35,E1-20-08-04,E1,ES01-004-C-01,ES01-004-C-00,ES01,IBE,-,-
3,62,E1-20-08-05,E1,ES01-005-C-01,ES01-005-C-00,ES01,IBE,-,-
4,44,E1-20-08-07,E1,ES01-007-C-01,ES01-007-C-00,ES01,IBE,-,-
...,...,...,...,...,...,...,...,...,...
206,804,47-Port-5,Port,ES25-005-S-99,ES25-005-S-01,ES25,IBE,-,-
207,805,49-Port-6,Port,ES25-006-S-99,ES25-006-S-01,ES25,IBE,-,-
208,806,51-Port-7,Port,ES25-007-S-99,ES25-007-S-01,ES25,IBE,-,-
209,807,53-Port-8,Port,ES25-008-S-99,ES25-008-S-01,ES25,IBE,-,-
210,808,55-Port-9,port,ES25-009-S-99,ES25-009-S-01,ES25,IBE,-,-

In [66]:
sample_id=[]
for i in names_info.index:
    sample_id.append(names_info[4][i].lstrip()[:13])

In [67]:
names_info["sample_id"]=sample_id

In [42]:
names_info

,0,1,2,3,4,5,6,7,8,sample_id
0,1,E1-20-08-01,E1,ES01-001-C-01,ES01-001-C-00,ES01,IBE,-,-,ES01-001-C-00
1,97,E1-20-08-08-1,E1,ES01-001-S-00-W,ES01-001-S-00-W,ES01,IBE,-,-,ES01-001-S-00
2,35,E1-20-08-04,E1,ES01-004-C-01,ES01-004-C-00,ES01,IBE,-,-,ES01-004-C-00
3,62,E1-20-08-05,E1,ES01-005-C-01,ES01-005-C-00,ES01,IBE,-,-,ES01-005-C-00
4,44,E1-20-08-07,E1,ES01-007-C-01,ES01-007-C-00,ES01,IBE,-,-,ES01-007-C-00
...,...,...,...,...,...,...,...,...,...,...
206,804,47-Port-5,Port,ES25-005-S-99,ES25-005-S-01,ES25,IBE,-,-,ES25-005-S-01
207,805,49-Port-6,Port,ES25-006-S-99,ES25-006-S-01,ES25,IBE,-,-,ES25-006-S-01
208,806,51-Port-7,Port,ES25-007-S-99,ES25-007-S-01,ES25,IBE,-,-,ES25-007-S-01
209,807,53-Port-8,Port,ES25-008-S-99,ES25-008-S-01,ES25,IBE,-,-,ES25-008-S-01
210,808,55-Port-9,port,ES25-009-S-99,ES25-009-S-01,ES25,IBE,-,-,ES25-009-S-01

In [69]:
names_info=names_info[[0, "sample_id"]]

In [70]:
names_info.columns=["BGI code", "Plant ID"]

In [71]:
names_info

    BGI code       Plant ID
0          1  ES01-001-C-00
1         97  ES01-001-S-00
2         35  ES01-004-C-00
3         62  ES01-005-C-00
4         44  ES01-007-C-00
..       ...            ...
206      804  ES25-005-S-01
207      805  ES25-006-S-01
208      806  ES25-007-S-01
209      807  ES25-008-S-01
210      808  ES25-009-S-01

[211 rows x 2 columns]

In [16]:
df.columns=["BGI code", "pop"]

In [46]:
env

,Plant ID,Latitude,Longitude,bio_1_Annual_Mean_Temperature,bio_2_Mean_Diurnal_Range,bio_3_Isothermality,bio_4_Temperature_Seasonality,bio_5_Max_Temperature_of_Warmest_Month,bio_6_Min_Temperature_of_Coldest_Month,bio_7_Temperature_Annual_Range,...,wind_Apr,wind_May,wind_Jun,wind_Jul,wind_Aug,wind_Sep,wind_Oct,wind_Nov,wind_Dec,Elev
0,ES01-001-C-00,42.993168,-5.910047,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,24.600000,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
1,ES01-004-C-00,42.993525,-5.910298,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,24.600000,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
2,ES01-005-C-00,42.992989,-5.909456,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,24.600000,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
3,ES01-007-C-00,42.993225,-5.910316,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,24.600000,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
4,ES01-008-S-00,42.993150,-5.910366,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,24.600000,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,ES25-005-S-01,43.153210,-3.569940,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,22.199999,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168
207,ES25-006-S-01,43.153210,-3.569940,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,22.199999,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168
208,ES25-007-S-01,43.153210,-3.569940,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,22.199999,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168
209,ES25-008-S-01,43.153210,-3.569940,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,22.199999,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168
210,ES25-009-S-01,43.153210,-3.569940,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,22.199999,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168

In [47]:
print(env.columns)

Index(['Plant ID', 'Latitude', 'Longitude', 'bio_1_Annual_Mean_Temperature',
       'bio_2_Mean_Diurnal_Range', 'bio_3_Isothermality',
       'bio_4_Temperature_Seasonality',
       'bio_5_Max_Temperature_of_Warmest_Month',
       'bio_6_Min_Temperature_of_Coldest_Month',
       'bio_7_Temperature_Annual_Range',
       'bio_8_Mean_Temperature_of_Wettest_Quarter',
       'bio_9_Mean_Temperature_of_Driest_Quarter',
       'bio_10_Mean_Temperature_of_Warmest_Quarter',
       'bio_11_Mean_Temperature_of_Coldest_Quarter',
       'bio_12_Annual_Precipitation', 'bio_13_Precipitation_of_Wettest_Month',
       'bio_14_Precipitation_of_Driest_Month',
       'bio_15_Precipitation_Seasonality',
       'bio_16_Precipitation_of_Wettest_Quarter',
       'bio_17_Precipitation_of_Driest_Quarter',
       'bio_18_Precipitation_of_Warmest_Quarter',
       'bio_19_Precipitation_of_Coldest_Quarter', 'tavg_Jan', 'tavg_Feb',
       'tavg_Mar', 'tavg_Apr', 'tavg_May', 'tavg_Jun', 'tavg_Jul', 'tavg_Aug',
       'tavg_Sep', 'tavg_Oct', 'tavg_Nov', 'tavg_Dec', 'prec_Jan', 'prec_Feb',
       'prec_Mar', 'prec_Apr', 'prec_May', 'prec_Jun', 'prec_Jul', 'prec_Aug',
       'prec_Sep', 'prec_Oct', 'prec_Nov', 'prec_Dec', 'ai_Jan', 'ai_Feb',
       'ai_Mar', 'ai_Apr', 'ai_May', 'ai_Jun', 'ai_Jul', 'ai_Aug', 'ai_Sep',
       'ai_Oct', 'ai_Nov', 'ai_Dec', 'srad_Jan', 'srad_Feb', 'srad_Mar',
       'srad_Apr', 'srad_May', 'srad_Jun', 'srad_Jul', 'srad_Aug', 'srad_Sep',
       'srad_Oct', 'srad_Nov', 'srad_Dec', 'vapr_Jan', 'vapr_Feb', 'vapr_Mar',
       'vapr_Apr', 'vapr_May', 'vapr_Jun', 'vapr_Jul', 'vapr_Aug', 'vapr_Sep',
       'vapr_Oct', 'vapr_Nov', 'vapr_Dec', 'wind_Jan', 'wind_Feb', 'wind_Mar',
       'wind_Apr', 'wind_May', 'wind_Jun', 'wind_Jul', 'wind_Aug', 'wind_Sep',
       'wind_Oct', 'wind_Nov', 'wind_Dec', 'Elev'],
      dtype='object')

In [85]:
a=pd.merge(names_info,env,on="Plant ID")

In [78]:
a

,BGI code,Plant ID,Latitude,Longitude,bio_1_Annual_Mean_Temperature,bio_2_Mean_Diurnal_Range,bio_3_Isothermality,bio_4_Temperature_Seasonality,bio_5_Max_Temperature_of_Warmest_Month,bio_6_Min_Temperature_of_Coldest_Month,...,wind_Apr,wind_May,wind_Jun,wind_Jul,wind_Aug,wind_Sep,wind_Oct,wind_Nov,wind_Dec,Elev
0,1,ES01-001-C-00,42.993168,-5.910047,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
1,35,ES01-004-C-00,42.993525,-5.910298,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
2,62,ES01-005-C-00,42.992989,-5.909456,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
3,44,ES01-007-C-00,42.993225,-5.910316,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
4,43,ES01-009-C-00,42.992791,-5.910154,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,804,ES25-005-S-01,43.153210,-3.569940,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168
204,805,ES25-006-S-01,43.153210,-3.569940,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168
205,806,ES25-007-S-01,43.153210,-3.569940,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168
206,807,ES25-008-S-01,43.153210,-3.569940,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168
207,808,ES25-009-S-01,43.153210,-3.569940,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168

In [73]:
set1=set(names_info["Plant ID"].astype(str))

In [74]:
set2=set(env["Plant ID"].astype(str))

In [75]:
set1-set2

{'ES01-001-S-00', 'ES04-037-S-01', 'ES06-008-S-01'}

In [76]:
set2-set1

{'ES01-008-S-00', 'ES04-057-S-01', 'ES06-040-S-01'}

In [80]:
names_info=names_info.replace('ES01-001-S-00','ES01-008-S-00')

In [81]:
names_info=names_info.replace('ES04-037-S-01','ES04-057-S-01')

In [82]:
names_info=names_info.replace('ES06-008-S-01','ES06-040-S-01')

In [83]:
set1=set(names_info["Plant ID"].astype(str))

In [84]:
set1-set2

set()

In [86]:
a=pd.merge(names_info,env,on="Plant ID")

In [87]:
a

,BGI code,Plant ID,Latitude,Longitude,bio_1_Annual_Mean_Temperature,bio_2_Mean_Diurnal_Range,bio_3_Isothermality,bio_4_Temperature_Seasonality,bio_5_Max_Temperature_of_Warmest_Month,bio_6_Min_Temperature_of_Coldest_Month,...,wind_Apr,wind_May,wind_Jun,wind_Jul,wind_Aug,wind_Sep,wind_Oct,wind_Nov,wind_Dec,Elev
0,1,ES01-001-C-00,42.993168,-5.910047,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
1,97,ES01-008-S-00,42.993150,-5.910366,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
2,35,ES01-004-C-00,42.993525,-5.910298,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
3,62,ES01-005-C-00,42.992989,-5.909456,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
4,44,ES01-007-C-00,42.993225,-5.910316,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,804,ES25-005-S-01,43.153210,-3.569940,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168
207,805,ES25-006-S-01,43.153210,-3.569940,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168
208,806,ES25-007-S-01,43.153210,-3.569940,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168
209,807,ES25-008-S-01,43.153210,-3.569940,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168
210,808,ES25-009-S-01,43.153210,-3.569940,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168

In [88]:
env=a[["BGI code"]+list(a.columns)[4:]]

In [89]:
env

,BGI code,bio_1_Annual_Mean_Temperature,bio_2_Mean_Diurnal_Range,bio_3_Isothermality,bio_4_Temperature_Seasonality,bio_5_Max_Temperature_of_Warmest_Month,bio_6_Min_Temperature_of_Coldest_Month,bio_7_Temperature_Annual_Range,bio_8_Mean_Temperature_of_Wettest_Quarter,bio_9_Mean_Temperature_of_Driest_Quarter,...,wind_Apr,wind_May,wind_Jun,wind_Jul,wind_Aug,wind_Sep,wind_Oct,wind_Nov,wind_Dec,Elev
0,1,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,24.600000,0.883333,13.933333,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
1,97,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,24.600000,0.883333,13.933333,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
2,35,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,24.600000,0.883333,13.933333,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
3,62,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,24.600000,0.883333,13.933333,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
4,44,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,24.600000,0.883333,13.933333,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,804,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,22.199999,4.100000,15.350000,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168
207,805,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,22.199999,4.100000,15.350000,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168
208,806,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,22.199999,4.100000,15.350000,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168
209,807,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,22.199999,4.100000,15.350000,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168
210,808,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,22.199999,4.100000,15.350000,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168

In [92]:
lat_lon=a[["BGI code","Latitude","Longitude"]]

In [93]:
env

,BGI code,bio_1_Annual_Mean_Temperature,bio_2_Mean_Diurnal_Range,bio_3_Isothermality,bio_4_Temperature_Seasonality,bio_5_Max_Temperature_of_Warmest_Month,bio_6_Min_Temperature_of_Coldest_Month,bio_7_Temperature_Annual_Range,bio_8_Mean_Temperature_of_Wettest_Quarter,bio_9_Mean_Temperature_of_Driest_Quarter,...,wind_Apr,wind_May,wind_Jun,wind_Jul,wind_Aug,wind_Sep,wind_Oct,wind_Nov,wind_Dec,Elev
0,1,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,24.600000,0.883333,13.933333,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
1,97,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,24.600000,0.883333,13.933333,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
2,35,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,24.600000,0.883333,13.933333,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
3,62,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,24.600000,0.883333,13.933333,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
4,44,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,24.600000,0.883333,13.933333,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,804,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,22.199999,4.100000,15.350000,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168
207,805,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,22.199999,4.100000,15.350000,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168
208,806,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,22.199999,4.100000,15.350000,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168
209,807,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,22.199999,4.100000,15.350000,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168
210,808,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,22.199999,4.100000,15.350000,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168

In [94]:
df["BGI code"]=df["BGI code"].astype(str)

C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\1277985422.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["BGI code"]=df["BGI code"].astype(str)

In [95]:
env["BGI code"]=env["BGI code"].astype(str)

C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\1157915990.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  env["BGI code"]=env["BGI code"].astype(str)

In [96]:
whole=pd.merge(df[["BGI code"]],env,on="BGI code")

In [97]:
whole

,BGI code,bio_1_Annual_Mean_Temperature,bio_2_Mean_Diurnal_Range,bio_3_Isothermality,bio_4_Temperature_Seasonality,bio_5_Max_Temperature_of_Warmest_Month,bio_6_Min_Temperature_of_Coldest_Month,bio_7_Temperature_Annual_Range,bio_8_Mean_Temperature_of_Wettest_Quarter,bio_9_Mean_Temperature_of_Driest_Quarter,...,wind_Apr,wind_May,wind_Jun,wind_Jul,wind_Aug,wind_Sep,wind_Oct,wind_Nov,wind_Dec,Elev
0,1,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,24.600000,0.883333,13.933333,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
1,97,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,24.600000,0.883333,13.933333,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
2,35,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,24.600000,0.883333,13.933333,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
3,62,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,24.600000,0.883333,13.933333,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
4,44,6.362500,8.425000,34.247967,587.282349,21.200001,-3.4,24.600000,0.883333,13.933333,...,5.9,5.0,4.2,4.1,4.1,4.2,5.0,5.6,6.1,1702
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,804,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,22.199999,4.100000,15.350000,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168
207,805,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,22.199999,4.100000,15.350000,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168
208,806,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,22.199999,4.100000,15.350000,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168
209,807,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,22.199999,4.100000,15.350000,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168
210,808,8.804167,8.908334,40.127628,499.360748,21.900000,-0.3,22.199999,4.100000,15.350000,...,4.1,3.7,3.3,3.2,3.1,3.1,3.7,4.1,4.4,1168

In [98]:
env=whole

In [99]:
distances={}
distances["ind1"]=[]
distances["ind2"]=[]
distances["distance"]=[]
for i in env.index:
    for j in env.index[i+1:]:
        distance=canberra(env.iloc[i][1:], env.iloc[j][1:])
        distances["ind1"].append(env["BGI code"][i])
        distances["ind2"].append(env["BGI code"][j])
        distances["distance"].append(distance)

In [100]:
canberra(env.iloc[0][1:], env.iloc[203][1:])

14.59026290838311

In [101]:
canberrra_distances=pd.DataFrame(distances)

In [103]:
canberrra_distances.to_csv("canberra_distances_ind_comp.tsv", index=False,sep="\t")

In [104]:
lat_lon

    BGI code   Latitude  Longitude
0          1  42.993168  -5.910047
1         97  42.993150  -5.910366
2         35  42.993525  -5.910298
3         62  42.992989  -5.909456
4         44  42.993225  -5.910316
..       ...        ...        ...
206      804  43.153210  -3.569940
207      805  43.153210  -3.569940
208      806  43.153210  -3.569940
209      807  43.153210  -3.569940
210      808  43.153210  -3.569940

[211 rows x 3 columns]

In [105]:
lat_lon["BGI code"]=lat_lon["BGI code"].astype(str)

C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\3011945036.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lat_lon["BGI code"]=lat_lon["BGI code"].astype(str)

In [106]:
whole=pd.merge(df[["BGI code"]],lat_lon,on="BGI code")

In [107]:
lat_lon=whole

In [108]:
distances={}
distances["ind1"]=[]
distances["ind2"]=[]
distances["distance"]=[]
for i in lat_lon.index:
    for j in lat_lon.index[i+1:]:
        distance=haversine.haversine(lat_lon.iloc[i][1:], lat_lon.iloc[j][1:])
        distances["ind1"].append(lat_lon["BGI code"][i])
        distances["ind2"].append(lat_lon["BGI code"][j])
        distances["distance"].append(distance)

In [109]:
haversine.haversine(tuple(lat_lon.iloc[0][1:]), tuple(lat_lon.iloc[1][1:]))

0.026021992466889177

In [110]:
distances

{'ind1': ['1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '97',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '35',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '62',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  '44',
  ...],
 'ind2': ['97',
  '35',
  '62',
  '44',
  '43',
  '98',
  '65',
  '51',
  '99',
  '100',
  '101',
  '77',
  '26',
  '25',
  '102',
  '123',
  '136',
  '133',
  '137',
  '734',
  '138',
  '139',
  '125',
  '105',
  '103',
  '135',
  '104',
  '2',
  '106',
  '21',
  '81',
  '27',
  '89',
  '90',
  '53',
  '141',
  '47',
  '56',
  '55',
  '126',
  '45',
  '3',
  '67B',
  '54',
  '142',
  '72',
  '28',
  '143',
  '52',
  '31',
  '68',
  '66',
  '69',
  '144',
  '107',
  '11',
  '85',
  '108',
  '887',
  '888',
  '889',
  '145',
  '146',
  '147',
  '140',
  '80',
  '39',
  '78',
  '86',
  '29',
  '92',
  '60',
  '59',
  '76',
  '94',
  '18',
  '30',
  '4',
  '46',
  '49',
  '48',
  '32',
  '38',
  '83',
  '109',
  '14',
  '127',
  '110',
  '42',
  '74',
  '15',
  '16',
  '57',
  '148',
  '71',
  '96',
  '87',
  '50',
  '149',
  '91',
  '890',
  '891',
  '892',
  '128',
  '893',
  '894',
  '150',
  '151',
  '152',
  '129',
  '153',
  '131',
  '132',
  '73',
  '112',
  '20',
  '9',
  '17',
  '82',
  '23',
  '117',
  '84',
  '111',
  '113',
  '114',
  '115',
  '116',
  '19',
  '70',
  '61',
  '5',
  '95',
  '22',
  '118',
  '171',
  '170',
  '34',
  '119',
  '120',
  '6',
  '75',
  '36',
  '169',
  '79',
  '168',
  '63',
  '121',
  '895',
  '896',
  '897',
  '898',
  '167',
  '899',
  '900',
  '901',
  '902',
  '164',
  '163',
  '162',
  '178',
  '177',
  '176',
  '175',
  '174',
  '727',
  '173',
  '726',
  '725',
  '728',
  '179',
  '134',
  '88',
  '41',
  '7',
  '10',
  '181',
  '122',
  '33',
  '40',
  '64',
  '13',
  '12',
  '58',
  '37B',
  '8',
  '93',
  '24',
  '903',
  '904',
  '905',
  '906',
  '907',
  '8522106001051',
  '8522106001053',
  '8522106001055',
  '8522106001058',
  '8522106001060',
  '683',
  '684',
  '685',
  '686',
  '688',
  '689',
  '690',
  '803',
  '804',
  '805',
  '806',
  '807',
  '808',
  '35',
  '62',
  '44',
  '43',
  '98',
  '65',
  '51',
  '99',
  '100',
  '101',
  '77',
  '26',
  '25',
  '102',
  '123',
  '136',
  '133',
  '137',
  '734',
  '138',
  '139',
  '125',
  '105',
  '103',
  '135',
  '104',
  '2',
  '106',
  '21',
  '81',
  '27',
  '89',
  '90',
  '53',
  '141',
  '47',
  '56',
  '55',
  '126',
  '45',
  '3',
  '67B',
  '54',
  '142',
  '72',
  '28',
  '143',
  '52',
  '31',
  '68',
  '66',
  '69',
  '144',
  '107',
  '11',
  '85',
  '108',
  '887',
  '888',
  '889',
  '145',
  '146',
  '147',
  '140',
  '80',
  '39',
  '78',
  '86',
  '29',
  '92',
  '60',
  '59',
  '76',
  '94',
  '18',
  '30',
  '4',
  '46',
  '49',
  '48',
  '32',
  '38',
  '83',
  '109',
  '14',
  '127',
  '110',
  '42',
  '74',
  '15',
  '16',
  '57',
  '148',
  '71',
  '96',
  '87',
  '50',
  '149',
  '91',
  '890',
  '891',
  '892',
  '128',
  '893',
  '894',
  '150',
  '151',
  '152',
  '129',
  '153',
  '131',
  '132',
  '73',
  '112',
  '20',
  '9',
  '17',
  '82',
  '23',
  '117',
  '84',
  '111',
  '113',
  '114',
  '115',
  '116',
  '19',
  '70',
  '61',
  '5',
  '95',
  '22',
  '118',
  '171',
  '170',
  '34',
  '119',
  '120',
  '6',
  '75',
  '36',
  '169',
  '79',
  '168',
  '63',
  '121',
  '895',
  '896',
  '897',
  '898',
  '167',
  '899',
  '900',
  '901',
  '902',
  '164',
  '163',
  '162',
  '178',
  '177',
  '176',
  '175',
  '174',
  '727',
  '173',
  '726',
  '725',
  '728',
  '179',
  '134',
  '88',
  '41',
  '7',
  '10',
  '181',
  '122',
  '33',
  '40',
  '64',
  '13',
  '12',
  '58',
  '37B',
  '8',
  '93',
  '24',
  '903',
  '904',
  '905',
  '906',
  '907',
  '8522106001051',
  '8522106001053',
  '8522106001055',
  '8522106001058',
  '8522106001060',
  '683',
  '684',
  '685',
  '686',
  '688',
  '689',
  '690',
  '803',
  '804',
  '805',
  '806',
  '807',
  '808',
  '62',
  '44',
  '43',
  '98',
  '65',
  '51',
  '99',
  '100',
  '101',
  '77',
  '26',
  '25',
  '102',
  '123',
  '136',
  '133',
  '137',
  '734',
  '138',
  '139',
  '125',
  '105',
  '103',
  '135',
  '104',
  '2',
  '106',
  '21',
  '81',
  '27',
  '89',
  '90',
  '53',
  '141',
  '47',
  '56',
  '55',
  '126',
  '45',
  '3',
  '67B',
  '54',
  '142',
  '72',
  '28',
  '143',
  '52',
  '31',
  '68',
  '66',
  '69',
  '144',
  '107',
  '11',
  '85',
  '108',
  '887',
  '888',
  '889',
  '145',
  '146',
  '147',
  '140',
  '80',
  '39',
  '78',
  '86',
  '29',
  '92',
  '60',
  '59',
  '76',
  '94',
  '18',
  '30',
  '4',
  '46',
  '49',
  '48',
  '32',
  '38',
  '83',
  '109',
  '14',
  '127',
  '110',
  '42',
  '74',
  '15',
  '16',
  '57',
  '148',
  '71',
  '96',
  '87',
  '50',
  '149',
  '91',
  '890',
  '891',
  '892',
  '128',
  '893',
  '894',
  '150',
  '151',
  '152',
  '129',
  '153',
  '131',
  '132',
  '73',
  '112',
  '20',
  '9',
  '17',
  '82',
  '23',
  '117',
  '84',
  '111',
  '113',
  '114',
  '115',
  '116',
  '19',
  '70',
  '61',
  '5',
  '95',
  '22',
  '118',
  '171',
  '170',
  '34',
  '119',
  '120',
  '6',
  '75',
  '36',
  '169',
  '79',
  '168',
  '63',
  '121',
  '895',
  '896',
  '897',
  '898',
  '167',
  '899',
  '900',
  '901',
  '902',
  '164',
  '163',
  '162',
  '178',
  '177',
  '176',
  '175',
  '174',
  '727',
  '173',
  '726',
  '725',
  '728',
  '179',
  '134',
  '88',
  '41',
  '7',
  '10',
  '181',
  '122',
  '33',
  '40',
  '64',
  '13',
  '12',
  '58',
  '37B',
  '8',
  '93',
  '24',
  '903',
  '904',
  '905',
  '906',
  '907',
  '8522106001051',
  '8522106001053',
  '8522106001055',
  '8522106001058',
  '8522106001060',
  '683',
  '684',
  '685',
  '686',
  '688',
  '689',
  '690',
  '803',
  '804',
  '805',
  '806',
  '807',
  '808',
  '44',
  '43',
  '98',
  '65',
  '51',
  '99',
  '100',
  '101',
  '77',
  '26',
  '25',
  '102',
  '123',
  '136',
  '133',
  '137',
  '734',
  '138',
  '139',
  '125',
  '105',
  '103',
  '135',
  '104',
  '2',
  '106',
  '21',
  '81',
  '27',
  '89',
  '90',
  '53',
  '141',
  '47',
  '56',
  '55',
  '126',
  '45',
  '3',
  '67B',
  '54',
  '142',
  '72',
  '28',
  '143',
  '52',
  '31',
  '68',
  '66',
  '69',
  '144',
  '107',
  '11',
  '85',
  '108',
  '887',
  '888',
  '889',
  '145',
  '146',
  '147',
  '140',
  '80',
  '39',
  '78',
  '86',
  '29',
  '92',
  '60',
  '59',
  '76',
  '94',
  '18',
  '30',
  '4',
  '46',
  '49',
  '48',
  '32',
  '38',
  '83',
  '109',
  '14',
  '127',
  '110',
  '42',
  '74',
  '15',
  '16',
  '57',
  '148',
  '71',
  '96',
  '87',
  '50',
  '149',
  '91',
  '890',
  '891',
  '892',
  '128',
  '893',
  '894',
  '150',
  '151',
  '152',
  '129',
  '153',
  '131',
  '132',
  '73',
  '112',
  '20',
  '9',
  '17',
  '82',
  '23',
  '117',
  '84',
  '111',
  '113',
  '114',
  '115',
  '116',
  '19',
  '70',
  '61',
  '5',
  '95',
  '22',
  '118',
  '171',
  '170',
  '34',
  '119',
  '120',
  '6',
  '75',
  '36',
  '169',
  '79',
  '168',
  '63',
  '121',
  '895',
  '896',
  '897',
  '898',
  '167',
  '899',
  '900',
  '901',
  '902',
  '164',
  '163',
  '162',
  '178',
  '177',
  '176',
  '175',
  '174',
  '727',
  '173',
  '726',
  '725',
  '728',
  '179',
  '134',
  '88',
  '41',
  '7',
  '10',
  '181',
  '122',
  '33',
  '40',
  '64',
  '13',
  '12',
  '58',
  '37B',
  '8',
  '93',
  '24',
  '903',
  '904',
  '905',
  '906',
  '907',
  '8522106001051',
  '8522106001053',
  '8522106001055',
  '8522106001058',
  '8522106001060',
  '683',
  '684',
  '685',
  '686',
  '688',
  '689',
  '690',
  '803',
  '804',
  '805',
  '806',
  '807',
  '808',
  '43',
  '98',
  '65',
  '51',
  '99',
  '100',
  '101',
  '77',
  '26',
  '25',
  '102',
  '123',
  '136',
  '133',
  '137',
  '734',
  '138',
  '139',
  '125',
  '105',
  '103',
  '135',
  '104',
  '2',
  '106',
  '21',
  '81',
  '27',
  '89',
  '90',
  '53',
  '141',
  '47',
  '56',
  '55',
  '126',
  '45',
  '3',
  '67B',
  '54',
  '142',
  '72',
  '28',
  '143',
  '52',
  '31',
  '68',
  '66',
  '69',
  '144',
  '107',
  '11',
  '85',
  '108',
  '887',
  '888',
  '889',
  '145',
  '146',
  '147',
  '140',
  '80',
  '39',
  '78',
  '86',
  '29',
  '92',
  '60',
  '59',
  '76',
  '94',
  '18',
  '30',
  '4',
  '46',
  '49',
  '48',
  '32',
  '38',
  '83',
  '109',
  '14',
  '127',
  '110',
  '42',
  '74',
  '15',
  '16',
  '57',
  '148',
  '71',
  '96',
  '87',
  '50',
  '149',
  '91',
  '890',
  '891',
  '892',
  '128',
  '893',
  '894',
  '150',
  '151',
  '152',
  '129',
  '153',
  '131',
  '132',
  '73',
  '112',
  '20',
  '9',
  '17',
  '82',
  '23',
  '117',
  '84',
  '111',
  '113',
  '114',
  '115',
  '116',
  '19',
  '70',
  '61',
  '5',
  '95',
  '22',
  '118',
  '171',
  '170',
  '34',
  '119',
  '120',
  '6',
  '75',
  '36',
  '169',
  '79',
  '168',
  '63',
  '121',
  '895',
  '896',
  '897',
  '898',
  '167',
  '899',
  '900',
  '901',
  '902',
  '164',
  '163',
  '162',
  '178',
  '177',
  '176',
  '175',
  '174',
  '727',
  '173',
  '726',
  '725',
  '728',
  '179',
  ...],
 'distance': [0.026021992466889177,
  0.04463816524379605,
  0.052025265177524926,
  0.02277787060205551,
  0.04281432537091011,
  0.040041367316963714,
  0.05134449913356932,
  0.07933789206451655,
  0.0801559113240159,
  0.13039209925518383,
  0.20173632108577952,
  0.0801358505828319,
  0.0801559113240159,
  0.47629038185202077,
  0.48773476990538966,
  0.10731989529382914,
  0.10731989529382914,
  0.10731989529382914,
  0.10731989529382914,
  0.10731989529382914,
  0.10731989529382914,
  0.10731989529382914,
  0.21402204031417393,
  12.16428014204203,
  12.158665494446028,
  11.57617268667829,
  13.41570238020336,
  13.497631182599891,
  26.166164460897267,
  26.204017944142524,
  26.356184479125698,
  26.416463279722763,
  26.416463279722763,
  26.44819247120718,
  26.45583148574875,
  26.419719064821628,
  26.44245991178145,
  26.521917265982093,
  26.51933751914984,
  26.419719064821628,
  26.545425784430194,
  26.59902419477986,
  26.698530251551365,
  26.69801376819995,
  26.419719064821628,
  25.570599809398445,
  25.58323891541454,
  26.419719064821628,
  25.58700690361175,
  25.58323891541454,
  25.72852305496851,
  25.738531214836417,
  25.747233056984502,
  26.419719064821628,
  26.20444151038474,
  26.59440571853472,
  26.616742372957166,
  26.608203914730435,
  26.34900199166293,
  26.344080969518807,
  26.299596407209243,
  26.419719064821628,
  26.419719064821628,
  26.419719064821628,
  26.419719064821628,
  17.06981890032765,
  17.03523762020171,
  17.03530068408464,
  17.04217369753654,
  16.934582579817413,
  16.93669155582443,
  17.06992132571568,
  17.075909153616326,
  17.056918792753326,
  17.130930175284984,
  17.137196625158168,
  17.1463144764582,
  17.141836656891996,
  17.13675406582688,
  17.14167019079663,
  17.05292202894739,
  17.042734599100307,
  17.043168244276924,
  17.150632881715843,
  16.933462231807248,
  16.929906471215002,
  17.064781494424125,
  16.930558805909985,
  16.91099684037201,
  16.910137451176837,
  16.902947134647455,
  16.900155911314812,
  16.924137326523763,
  17.064781494424125,
  17.02408966675436,
  17.028542542185935,
  17.01703266524058,
  17.031940014359755,
  17.064781494424125,
  17.01762427356291,
  17.15063680974844,
  16.858493581521028,
  16.88036238169053,
  17.064781494424125,
  17.42677759010194,
  17.42677759010194,
  17.064781494424125,
  17.064781494424125,
  17.064781494424125,
  17.064781494424125,
  17.064781494424125,
  17.064781494424125,
  17.064781494424125,
  28.303455470359655,
  28.32267313014387,
  28.467729920806185,
  28.469306266014964,
  28.484496452472058,
  28.109268926294877,
  28.115250809912176,
  27.985801827740843,
  27.94931765026282,
  28.34723355163298,
  28.34064596707742,
  28.33326099648032,
  28.397476609376973,
  28.454353579686256,
  28.482938819512025,
  28.5433046314613,
  28.097698084288524,
  28.08474639800593,
  27.99045320042793,
  28.001798803584375,
  28.02351994028515,
  1.6114458947373016,
  1.6114458947373016,
  1.6155443596407508,
  1.6412171239649942,
  1.6586441315845228,
  1.6586441315845228,
  1.7130030742527447,
  1.7261894822034285,
  1.6114458947373016,
  1.7398735251641195,
  1.6114458947373016,
  1.819268563361724,
  1.819268563361724,
  1.657406642152711,
  1.672557587715053,
  1.7447427280071564,
  1.7352506136918266,
  1.6114458947373016,
  1.9355079217691467,
  1.948000873845896,
  1.9481858306168616,
  1.7568353652095992,
  1.6114458947373016,
  1.6114458947373016,

In [111]:
harvesine_distances=pd.DataFrame(distances)

In [112]:
harvesine_distances

      ind1 ind2  distance
0        1   97  0.026022
1        1   35  0.044638
2        1   62  0.052025
3        1   44  0.022778
4        1   43  0.042814
...    ...  ...       ...
22150  805  807  0.000000
22151  805  808  0.000000
22152  806  807  0.000000
22153  806  808  0.000000
22154  807  808  0.000000

[22155 rows x 3 columns]

In [113]:
harvesine_distances.to_csv("harvesine_distances_ind_comp.tsv", index=False,sep="\t")

In [114]:
harvesine_distances

      ind1 ind2  distance
0        1   97  0.026022
1        1   35  0.044638
2        1   62  0.052025
3        1   44  0.022778
4        1   43  0.042814
...    ...  ...       ...
22150  805  807  0.000000
22151  805  808  0.000000
22152  806  807  0.000000
22153  806  808  0.000000
22154  807  808  0.000000

[22155 rows x 3 columns]

In [115]:
canberrra_distances

      ind1 ind2  distance
0        1   97       0.0
1        1   35       0.0
2        1   62       0.0
3        1   44       0.0
4        1   43       0.0
...    ...  ...       ...
22150  805  807       0.0
22151  805  808       0.0
22152  806  807       0.0
22153  806  808       0.0
22154  807  808       0.0

[22155 rows x 3 columns]

In [116]:
pop=list(lat_lon["BGI code"])

In [117]:
empty=pd.DataFrame(columns=pop, index=pop)

In [118]:
empty=empty.fillna(0)

C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\3573789790.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  empty=empty.fillna(0)

In [119]:
empty

,1,97,35,62,44,43,98,65,51,99,...,686,688,689,690,803,804,805,806,807,808
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
97,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
62,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
44,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
804,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
805,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
806,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
807,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
808,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [120]:
for i in canberrra_distances.index:
    empty[canberrra_distances["ind1"][i]][canberrra_distances["ind2"][i]]=empty[canberrra_distances["ind1"][i]][canberrra_distances["ind2"][i]]+canberrra_distances["distance"][i]
    empty[canberrra_distances["ind2"][i]][canberrra_distances["ind1"][i]]=empty[canberrra_distances["ind2"][i]][canberrra_distances["ind1"][i]]+canberrra_distances["distance"][i]

C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\791766984.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  empty[canberrra_distances["ind1"][i]][canberrra_distances["ind2"][i]]=empty[canberrra_distances["ind1"][i]][canberrra_distances["ind2"][i]]+canberrra_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\791766984.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  empty[canberrra_distances["ind2"][i]][canberrra_distances["ind1"][i]]=empty[canberrra_distances["ind2"][i]][canberrra_distances["ind1"][i]]+canberrra_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\791766984.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  empty[canberrra_distances["ind1"][i]][canberrra_distances["ind2"][i]]=empty[canberrra_distances["ind1"][i]][canberrra_distances["ind2"][i]]+canberrra_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\791766984.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  empty[canberrra_distances["ind2"][i]][canberrra_distances["ind1"][i]]=empty[canberrra_distances["ind2"][i]][canberrra_distances["ind1"][i]]+canberrra_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\791766984.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  empty[canberrra_distances["ind1"][i]][canberrra_distances["ind2"][i]]=empty[canberrra_distances["ind1"][i]][canberrra_distances["ind2"][i]]+canberrra_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\791766984.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  empty[canberrra_distances["ind2"][i]][canberrra_distances["ind1"][i]]=empty[canberrra_distances["ind2"][i]][canberrra_distances["ind1"][i]]+canberrra_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\791766984.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  empty[canberrra_distances["ind1"][i]][canberrra_distances["ind2"][i]]=empty[canberrra_distances["ind1"][i]][canberrra_distances["ind2"][i]]+canberrra_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\791766984.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  empty[canberrra_distances["ind2"][i]][canberrra_distances["ind1"][i]]=empty[canberrra_distances["ind2"][i]][canberrra_distances["ind1"][i]]+canberrra_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\791766984.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  empty[canberrra_distances["ind1"][i]][canberrra_distances["ind2"][i]]=empty[canberrra_distances["ind1"][i]][canberrra_distances["ind2"][i]]+canberrra_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\791766984.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  empty[canberrra_distances["ind2"][i]][canberrra_distances["ind1"][i]]=empty[canberrra_distances["ind2"][i]][canberrra_distances["ind1"][i]]+canberrra_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\791766984.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  empty[canberrra_distances["ind1"][i]][canberrra_distances["ind2"][i]]=empty[canberrra_distances["ind1"][i]][canberrra_distances["ind2"][i]]+canberrra_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\791766984.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  empty[canberrra_distances["ind2"][i]][canberrra_distances["ind1"][i]]=empty[canberrra_distances["ind2"][i]][canberrra_distances["ind1"][i]]+canberrra_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\791766984.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  empty[canberrra_distances["ind1"][i]][canberrra_distances["ind2"][i]]=empty[canberrra_distances["ind1"][i]][canberrra_distances["ind2"][i]]+canberrra_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\791766984.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  empty[canberrra_distances["ind2"][i]][canberrra_distances["ind1"][i]]=empty[canberrra_distances["ind2"][i]][canberrra_distances["ind1"][i]]+canberrra_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\791766984.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  empty[canberrra_distances["ind1"][i]][canberrra_distances["ind2"][i]]=empty[canberrra_distances["ind1"][i]][canberrra_distances["ind2"][i]]+canberrra_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\791766984.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  empty[canberrra_distances["ind2"][i]][canberrra_distances["ind1"][i]]=empty[canberrra_distances["ind2"][i]][canberrra_distances["ind1"][i]]+canberrra_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\791766984.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  empty[canberrra_distances["ind1"][i]][canberrra_distances["ind2"][i]]=empty[canberrra_distances["ind1"][i]][canberrra_distances["ind2"][i]]+canberrra_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\791766984.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  empty[canberrra_distances["ind2"][i]][canberrra_distances["ind1"][i]]=empty[canberrra_distances["ind2"][i]][canberrra_distances["ind1"][i]]+canberrra_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\791766984.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  empty[canberrra_distances["ind1"][i]][canberrra_distances["ind2"][i]]=empty[canberrra_distances["ind1"][i]][canberrra_distances["ind2"][i]]+canberrra_distances["distance"][i]

In [121]:
empty

,1,97,35,62,44,43,98,65,51,99,...,686,688,689,690,803,804,805,806,807,808
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,6.109847,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263
97,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,6.109847,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263
35,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,6.109847,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263
62,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,6.109847,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263
44,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,6.109847,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
804,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,...,11.284808,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
805,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,...,11.284808,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
806,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,...,11.284808,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
807,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,...,11.284808,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
808,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,14.590263,...,11.284808,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [122]:
empty.to_csv("canberra_distances_square_ind_comp.tsv",sep="\t")

In [123]:
empty=pd.DataFrame(columns=pop, index=pop)
empty=empty.fillna(0)

C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\2646264829.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  empty=empty.fillna(0)

In [124]:
for i in harvesine_distances.index:
    empty[harvesine_distances["ind1"][i]][harvesine_distances["ind2"][i]]=empty[harvesine_distances["ind1"][i]][harvesine_distances["ind2"][i]]+harvesine_distances["distance"][i]
    empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]=empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]+harvesine_distances["distance"][i]

C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\3302506750.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  empty[harvesine_distances["ind1"][i]][harvesine_distances["ind2"][i]]=empty[harvesine_distances["ind1"][i]][harvesine_distances["ind2"][i]]+harvesine_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\3302506750.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.026021992466889177' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  empty[harvesine_distances["ind1"][i]][harvesine_distances["ind2"][i]]=empty[harvesine_distances["ind1"][i]][harvesine_distances["ind2"][i]]+harvesine_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\3302506750.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]=empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]+harvesine_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\3302506750.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]=empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]+harvesine_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\3302506750.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.026021992466889177' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]=empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]+harvesine_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\3302506750.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]=empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]+harvesine_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\3302506750.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]=empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]+harvesine_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\3302506750.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.04463816524379605' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]=empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]+harvesine_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\3302506750.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]=empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]+harvesine_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\3302506750.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]=empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]+harvesine_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\3302506750.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.052025265177524926' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]=empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]+harvesine_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\3302506750.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]=empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]+harvesine_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\3302506750.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]=empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]+harvesine_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\3302506750.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.02277787060205551' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]=empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]+harvesine_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\3302506750.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]=empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]+harvesine_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\3302506750.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]=empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]+harvesine_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\3302506750.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.04281432537091011' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]=empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]+harvesine_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\3302506750.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]=empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]+harvesine_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\3302506750.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]=empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]+harvesine_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\3302506750.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.040041367316963714' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]=empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]+harvesine_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\3302506750.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]=empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]+harvesine_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\3302506750.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]=empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]+harvesine_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\3302506750.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.05134449913356932' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]=empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]+harvesine_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\3302506750.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]=empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]+harvesine_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\3302506750.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]=empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]+harvesine_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\3302506750.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.07933789206451655' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]=empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]+harvesine_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\3302506750.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]=empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]+harvesine_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\3302506750.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]=empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]+harvesine_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\3302506750.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.0801559113240159' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]=empty[harvesine_distances["ind2"][i]][harvesine_distances["ind1"][i]]+harvesine_distances["distance"][i]
C:\Users\mmehak\AppData\Local\Temp\ipykernel_61600\3302506750.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!

In [125]:
empty

,1,97,35,62,44,43,98,65,51,99,...,686,688,689,690,803,804,805,806,807,808
1,0.000000,0.026022,0.044638,0.052025,0.022778,0.042814,0.040041,0.051344,0.079338,0.080156,...,125.871847,190.902403,190.902403,190.902403,190.902403,190.902403,190.902403,190.902403,190.902403,190.902403
97,0.026022,0.000000,0.042063,0.076147,0.009278,0.043484,0.034118,0.042591,0.061617,0.058308,...,125.897860,190.928413,190.928413,190.928413,190.928413,190.928413,190.928413,190.928413,190.928413,190.928413
35,0.044638,0.042063,0.000000,0.090785,0.033391,0.082453,0.075074,0.084437,0.101737,0.054001,...,125.890242,190.918454,190.918454,190.918454,190.918454,190.918454,190.918454,190.918454,190.918454,190.918454
62,0.052025,0.076147,0.090785,0.000000,0.074706,0.060890,0.068619,0.077558,0.110787,0.132180,...,125.824845,190.856745,190.856745,190.856745,190.856745,190.856745,190.856745,190.856745,190.856745,190.856745
44,0.022778,0.009278,0.033391,0.074706,0.000000,0.050025,0.041813,0.051053,0.070873,0.057606,...,125.893378,190.923477,190.923477,190.923477,190.923477,190.923477,190.923477,190.923477,190.923477,190.923477
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
804,190.902403,190.928413,190.918454,190.856745,190.923477,190.915549,190.924872,190.932493,190.964925,190.972393,...,65.625537,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
805,190.902403,190.928413,190.918454,190.856745,190.923477,190.915549,190.924872,190.932493,190.964925,190.972393,...,65.625537,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
806,190.902403,190.928413,190.918454,190.856745,190.923477,190.915549,190.924872,190.932493,190.964925,190.972393,...,65.625537,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
807,190.902403,190.928413,190.918454,190.856745,190.923477,190.915549,190.924872,190.932493,190.964925,190.972393,...,65.625537,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
808,190.902403,190.928413,190.918454,190.856745,190.923477,190.915549,190.924872,190.932493,190.964925,190.972393,...,65.625537,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [126]:
empty.to_csv("harvesine_distances_square_ind_comp.tsv",sep="\t")

In [127]:
df=pd.read_csv("N:/dep_coupland/grp_fulgione/mehak/data/spanish_project/ibe/matrix_alpina_pairwDiff_2024-06-30.txt", sep="\t", header=None)

In [128]:
df.head(5)

,0,1,2,3,4,5,6,7,8,9,...,998,999,1000,1001,1002,1003,1004,1005,1006,1007
0,0.000000,0.002771,0.001243,0.002484,0.002442,0.002615,0.002565,0.002742,0.002679,0.002748,...,0.006755,0.009290,0.009281,0.009293,0.009296,0.009278,0.009315,0.009362,0.009303,NaN
1,0.002771,0.000000,0.002790,0.002807,0.002885,0.002764,0.002804,0.002742,0.002500,0.002580,...,0.006716,0.009186,0.009172,0.009210,0.009179,0.009174,0.009210,0.009244,0.009199,NaN
2,0.001243,0.002790,0.000000,0.002480,0.002414,0.002699,0.002631,0.002786,0.002701,0.002773,...,0.006745,0.009285,0.009273,0.009297,0.009286,0.009263,0.009302,0.009347,0.009290,NaN
3,0.002484,0.002807,0.002480,0.000000,0.002537,0.002830,0.002548,0.002957,0.002733,0.002782,...,0.006679,0.009311,0.009308,0.009309,0.009296,0.009290,0.009333,0.009384,0.009311,NaN
4,0.002442,0.002885,0.002414,0.002537,0.000000,0.002852,0.002626,0.002941,0.002811,0.002920,...,0.006693,0.009262,0.009254,0.009264,0.009254,0.009245,0.009279,0.009332,0.009264,NaN

In [129]:
file=open("N:/dep_coupland/grp_fulgione/mehak/data/spanish_project/ibe/names_pi_matrix_alpina_2024-06-30.txt")

In [130]:
names=file.readlines()

In [131]:
names

['1\n',
 '10\n',
 '100\n',
 '101\n',
 '102\n',
 '103\n',
 '104\n',
 '105\n',
 '106\n',
 '107\n',
 '108\n',
 '109\n',
 '11\n',
 '110\n',
 '111\n',
 '112\n',
 '113\n',
 '114\n',
 '115\n',
 '116\n',
 '117\n',
 '118\n',
 '119\n',
 '12\n',
 '120\n',
 '121\n',
 '122\n',
 '123\n',
 '125\n',
 '126\n',
 '127\n',
 '128\n',
 '129\n',
 '13\n',
 '131\n',
 '132\n',
 '133\n',
 '134\n',
 '135\n',
 '136\n',
 '137\n',
 '138\n',
 '139\n',
 '14\n',
 '140\n',
 '141\n',
 '142\n',
 '143\n',
 '144\n',
 '145\n',
 '146\n',
 '147\n',
 '148\n',
 '149\n',
 '15\n',
 '150\n',
 '151\n',
 '151B\n',
 '152\n',
 '153\n',
 '16\n',
 '162\n',
 '163\n',
 '164\n',
 '165\n',
 '166\n',
 '167\n',
 '168\n',
 '169\n',
 '17\n',
 '170\n',
 '171\n',
 '172\n',
 '173\n',
 '174\n',
 '175\n',
 '176\n',
 '177\n',
 '178\n',
 '179\n',
 '18\n',
 '180\n',
 '181\n',
 '182\n',
 '183\n',
 '184\n',
 '186\n',
 '187\n',
 '188\n',
 '189\n',
 '19\n',
 '190\n',
 '191\n',
 '192\n',
 '193\n',
 '194\n',
 '195\n',
 '196\n',
 '197\n',
 '198\n',
 '199\n',
 '2\n',
 '20\n',
 '200\n',
 '201\n',
 '202\n',
 '203\n',
 '204\n',
 '205\n',
 '206\n',
 '207\n',
 '208\n',
 '209\n',
 '21\n',
 '210\n',
 '211\n',
 '212\n',
 '213\n',
 '215\n',
 '217\n',
 '218\n',
 '219\n',
 '22\n',
 '220\n',
 '221\n',
 '222\n',
 '223\n',
 '224\n',
 '225\n',
 '226\n',
 '227\n',
 '228\n',
 '229\n',
 '23\n',
 '230\n',
 '231\n',
 '232\n',
 '233\n',
 '234\n',
 '235\n',
 '236\n',
 '237\n',
 '238\n',
 '239\n',
 '24\n',
 '240\n',
 '241\n',
 '242\n',
 '243\n',
 '244\n',
 '245\n',
 '246\n',
 '247\n',
 '248\n',
 '249\n',
 '25\n',
 '250\n',
 '251\n',
 '252\n',
 '253\n',
 '254\n',
 '255\n',
 '256\n',
 '257\n',
 '258\n',
 '259\n',
 '26\n',
 '260\n',
 '261\n',
 '262\n',
 '263\n',
 '264\n',
 '265\n',
 '266\n',
 '267\n',
 '268\n',
 '269\n',
 '27\n',
 '270\n',
 '271\n',
 '272\n',
 '273\n',
 '274\n',
 '275\n',
 '276\n',
 '277\n',
 '278\n',
 '279\n',
 '28\n',
 '280\n',
 '281\n',
 '282\n',
 '283\n',
 '284\n',
 '285\n',
 '286\n',
 '287\n',
 '288\n',
 '289\n',
 '29\n',
 '290\n',
 '291\n',
 '292\n',
 '293\n',
 '294\n',
 '295\n',
 '296\n',
 '297\n',
 '298\n',
 '299\n',
 '3\n',
 '30\n',
 '300\n',
 '301\n',
 '302\n',
 '303\n',
 '304\n',
 '305\n',
 '306\n',
 '307\n',
 '308\n',
 '309\n',
 '31\n',
 '310\n',
 '311\n',
 '312\n',
 '313\n',
 '314\n',
 '315\n',
 '316\n',
 '317\n',
 '318\n',
 '319\n',
 '32\n',
 '320\n',
 '321\n',
 '322\n',
 '323\n',
 '324\n',
 '325\n',
 '326\n',
 '327\n',
 '328\n',
 '329\n',
 '33\n',
 '330\n',
 '331\n',
 '332\n',
 '333\n',
 '334\n',
 '335\n',
 '336\n',
 '337\n',
 '338\n',
 '339\n',
 '34\n',
 '340\n',
 '341\n',
 '342\n',
 '343\n',
 '344\n',
 '345\n',
 '346\n',
 '347\n',
 '348\n',
 '349\n',
 '35\n',
 '350\n',
 '351\n',
 '352\n',
 '353\n',
 '354\n',
 '355\n',
 '356\n',
 '357\n',
 '358\n',
 '359\n',
 '36\n',
 '360\n',
 '361\n',
 '362\n',
 '363\n',
 '364\n',
 '365\n',
 '366\n',
 '367\n',
 '368\n',
 '369\n',
 '370\n',
 '371\n',
 '372\n',
 '373\n',
 '374\n',
 '375\n',
 '376\n',
 '377\n',
 '378\n',
 '379\n',
 '37B\n',
 '38\n',
 '380\n',
 '381\n',
 '382\n',
 '383\n',
 '384\n',
 '385\n',
 '386\n',
 '387\n',
 '388\n',
 '389\n',
 '39\n',
 '390\n',
 '391\n',
 '392\n',
 '393\n',
 '394\n',
 '395\n',
 '396\n',
 '397\n',
 '398\n',
 '399\n',
 '4\n',
 '40\n',
 '400\n',
 '401\n',
 '402\n',
 '403\n',
 '404\n',
 '405\n',
 '406\n',
 '407\n',
 '408\n',
 '409\n',
 '41\n',
 '410\n',
 '411\n',
 '412\n',
 '413\n',
 '414\n',
 '415\n',
 '416\n',
 '417\n',
 '418\n',
 '419\n',
 '42\n',
 '420\n',
 '421\n',
 '422\n',
 '423\n',
 '424\n',
 '425\n',
 '426\n',
 '427\n',
 '428\n',
 '429\n',
 '43\n',
 '430\n',
 '431\n',
 '432\n',
 '433\n',
 '434\n',
 '435\n',
 '436\n',
 '437\n',
 '438\n',
 '439\n',
 '44\n',
 '440\n',
 '441\n',
 '442\n',
 '443\n',
 '444\n',
 '445\n',
 '446\n',
 '447\n',
 '448\n',
 '449\n',
 '45\n',
 '450\n',
 '451\n',
 '452\n',
 '453\n',
 '454\n',
 '455\n',
 '456\n',
 '457\n',
 '458\n',
 '459\n',
 '46\n',
 '460\n',
 '461\n',
 '462\n',
 '463\n',
 '464\n',
 '465\n',
 '466\n',
 '467\n',
 '468\n',
 '469\n',
 '47\n',
 '470\n',
 '471\n',
 '472\n',
 '473\n',
 '474\n',
 '475\n',
 '476\n',
 '477\n',
 '478\n',
 '479\n',
 '48\n',
 '480\n',
 '481\n',
 '482\n',
 '483\n',
 '484\n',
 '485\n',
 '486\n',
 '487\n',
 '488\n',
 '489\n',
 '49\n',
 '490\n',
 '491\n',
 '492\n',
 '493\n',
 '494\n',
 '495\n',
 '496\n',
 '497\n',
 '498\n',
 '499\n',
 '5\n',
 '50\n',
 '500\n',
 '501\n',
 '502\n',
 '503\n',
 '504\n',
 '505\n',
 '506\n',
 '507\n',
 '508\n',
 '509\n',
 '51\n',
 '510\n',
 '511\n',
 '512\n',
 '513\n',
 '514\n',
 '515\n',
 '516\n',
 '517\n',
 '518\n',
 '519\n',
 '52\n',
 '520\n',
 '521\n',
 '522\n',
 '523\n',
 '524\n',
 '525\n',
 '526\n',
 '527\n',
 '528\n',
 '529\n',
 '53\n',
 '530\n',
 '531\n',
 '532\n',
 '533\n',
 '534\n',
 '535\n',
 '536\n',
 '537\n',
 '538\n',
 '539\n',
 '54\n',
 '540\n',
 '541\n',
 '542\n',
 '543\n',
 '544\n',
 '545\n',
 '546\n',
 '547\n',
 '548\n',
 '549\n',
 '55\n',
 '550\n',
 '551\n',
 '552\n',
 '553\n',
 '554\n',
 '555\n',
 '556\n',
 '557\n',
 '558\n',
 '559\n',
 '56\n',
 '560\n',
 '561\n',
 '562\n',
 '563\n',
 '564\n',
 '565\n',
 '566\n',
 '567\n',
 '568\n',
 '569\n',
 '57\n',
 '570\n',
 '571\n',
 '572\n',
 '573\n',
 '574\n',
 '575\n',
 '576\n',
 '577\n',
 '578\n',
 '579\n',
 '58\n',
 '580\n',
 '581\n',
 '582\n',
 '583\n',
 '584\n',
 '585\n',
 '586\n',
 '587\n',
 '588\n',
 '589\n',
 '59\n',
 '590\n',
 '591\n',
 '592\n',
 '593\n',
 '594\n',
 '595\n',
 '596\n',
 '597\n',
 '598\n',
 '599\n',
 '6\n',
 '60\n',
 '600\n',
 '601\n',
 '602\n',
 '603\n',
 '604\n',
 '605\n',
 '606\n',
 '607\n',
 '608\n',
 '61\n',
 '610\n',
 '611\n',
 '612\n',
 '613\n',
 '614\n',
 '615\n',
 '616\n',
 '617\n',
 '618\n',
 '619\n',
 '62\n',
 '620\n',
 '621\n',
 '622\n',
 '623\n',
 '624\n',
 '625\n',
 '626\n',
 '627\n',
 '628\n',
 '629\n',
 '63\n',
 '630\n',
 '631\n',
 '632\n',
 '633\n',
 '634\n',
 '635\n',
 '636\n',
 '637\n',
 '638\n',
 '639\n',
 '64\n',
 '640\n',
 '641\n',
 '642\n',
 '643\n',
 '644\n',
 '646\n',
 '647\n',
 '648\n',
 '649\n',
 '65\n',
 '650\n',
 '651\n',
 '652\n',
 '653\n',
 '654\n',
 '656\n',
 '657\n',
 '658\n',
 '659\n',
 '66\n',
 '660\n',
 '661\n',
 '662\n',
 '663\n',
 '664\n',
 '665\n',
 '666\n',
 '667\n',
 '668\n',
 '669\n',
 '670\n',
 '671\n',
 '672\n',
 '673\n',
 '674\n',
 '675\n',
 '676\n',
 '677\n',
 '678\n',
 '679\n',
 '67B\n',
 '68\n',
 '680\n',
 '681\n',
 '682\n',
 '683\n',
 '684\n',
 '685\n',
 '686\n',
 '687\n',
 '688\n',
 '689\n',
 '69\n',
 '690\n',
 '691\n',
 '692\n',
 '693\n',
 '694\n',
 '695\n',
 '696\n',
 '697\n',
 '698\n',
 '699\n',
 '7\n',
 '70\n',
 '700\n',
 '701\n',
 '702\n',
 '703\n',
 '704\n',
 '705\n',
 '706\n',
 '707\n',
 '708\n',
 '709\n',
 '71\n',
 '710\n',
 '711\n',
 '712\n',
 '713\n',
 '714\n',
 '715\n',
 '716\n',
 '717\n',
 '718\n',
 '719\n',
 '72\n',
 '720\n',
 '721\n',
 '722\n',
 '723\n',
 '725\n',
 '726\n',
 '727\n',
 '728\n',
 '729\n',
 '73\n',
 '730\n',
 '731\n',
 '732\n',
 '733\n',
 '734\n',
 '735\n',
 '736\n',
 '737\n',
 '738\n',
 '739\n',
 '74\n',
 '740\n',
 '741\n',
 '742\n',
 '743\n',
 '744\n',
 '745\n',
 '746\n',
 '747\n',
 '748\n',
 '749\n',
 '75\n',
 '750\n',
 '751\n',
 '752\n',
 '753\n',
 '754\n',
 '755\n',
 '756\n',
 '757\n',
 '758\n',
 '759\n',
 '76\n',
 '760\n',
 '761\n',
 '762\n',
 '763\n',
 '764\n',
 '765\n',
 '766\n',
 '767\n',
 '768\n',
 '769\n',
 '77\n',
 '770\n',
 '771\n',
 '772\n',
 '773\n',
 '774\n',
 '775\n',
 '776\n',
 '777\n',
 '778\n',
 '779\n',
 '78\n',
 '780\n',
 '781\n',
 '782\n',
 '783\n',
 '784\n',
 '785\n',
 '786\n',
 '787\n',
 '788\n',
 '789\n',
 '79\n',
 '790\n',
 '791\n',
 '792\n',
 '793\n',
 '794\n',
 '795\n',
 '796\n',
 '797\n',
 '798\n',
 '799\n',
 '8\n',
 '80\n',
 '800\n',
 '801\n',
 '802\n',
 '803\n',
 '804\n',
 '805\n',
 '806\n',
 '807\n',
 '808\n',
 '809\n',
 '81\n',
 '810\n',
 '814\n',
 '815\n',
 '818\n',
 '819\n',
 '82\n',
 '83\n',
 '84\n',
 '85\n',
 '8522106001050\n',
 '8522106001051\n',
 '8522106001053\n',
 '8522106001055\n',
 '8522106001058\n',
 '8522106001060\n',
 '86\n',
 '87\n',
 '88\n',
 '89\n',
 '9\n',
 '90\n',
 '91\n',
 '92\n',
 '93\n',
 '94\n',
 '95\n',
 '96\n',
 '97\n',
 '98\n',
 '99\n',
 'SN7640069\n',
 '1000\n',
 '1001\n',
 '1002\n',
 '1003\n',
 '1004\n',
 '1005\n',
 '1006\n',
 '1007\n',
 '1008\n',
 '1009\n',
 '1010\n',
 '1011\n',
 '1012\n',
 '1013\n',
 '1014\n',
 '1015\n',
 '1016\n',
 '1017\n',
 '1018\n',
 '1019\n',
 '1020\n',
 '1021\n',
 '1022\n',
 '1023\n',
 '1024\n',
 '1025\n',
 '1026\n',
 '1027\n',
 '1031\n',
 '1032\n',
 '1034\n',
 '1047\n',
 '817\n',
 '820\n',
 '840\n',
 '841\n',
 '842\n',
 '843\n',
 '844\n',
 '845\n',
 '846\n',
 '847\n',
 '848\n',
 '849\n',
 '850\n',
 '851\n',
 '852\n',
 '853\n',
 '854\n',
 '855\n',
 '856\n',
 '857\n',
 '858\n',
 '859\n',
 '860\n',
 '861\n',
 '862\n',
 '863\n',
 '864\n',
 '865\n',
 '866\n',
 '867\n',
 '868\n',
 '869\n',
 '870\n',
 '871\n',
 '872\n',
 '873\n',
 '874\n',
 '875\n',
 '876\n',
 '877\n',
 '878\n',
 '879\n',
 '880\n',
 '881\n',
 '882\n',
 '883\n',
 '884\n',
 '885\n',
 '886\n',
 '887\n',
 '888\n',
 '889\n',
 '890\n',
 '891\n',
 '892\n',
 '893\n',
 '894\n',
 '895\n',
 '896\n',
 '897\n',
 '898\n',
 '899\n',
 '900\n',
 '901\n',
 '902\n',
 '903\n',
 '904\n',
 '905\n',
 '906\n',
 '907\n',
 '908\n',
 '909\n',
 '910\n',
 '911\n',
 '912\n',
 '913\n',
 '914\n',
 '915\n',
 '916\n',
 '917\n',
 '918\n',
 '919\n',
 '920\n',
 '921\n',
 '922\n',
 '923\n',
 '924\n',
 '925\n',
 '926\n',
 '927\n',
 '928\n',
 '929\n',
 '930\n',
 '931\n',
 '932\n',
 '933\n',
 '934\n',
 '935\n',
 '936\n',
 '937\n',
 '938\n',
 '939\n',
 '940\n',
 '941\n',
 '942\n',
 '943\n',
 '944\n',
 '945\n',
 '946\n',
 '947\n',
 '948\n',
 '949\n',
 '950\n',
 '951\n',
 '952\n',
 '953\n',
 '954\n',
 '955\n',
 '956\n',
 '957\n',
 '958\n',
 '959\n',
 '960\n',
 '961\n',
 '962\n',
 '963\n',
 '964\n',
 '965\n',
 '966\n',
 '967\n',
 '968\n',
 '969\n',
 '970\n',
 '971\n',
 '972\n',
 '973\n',
 '974\n',
 '975\n',
 '976\n',
 '977\n',
 '978\n',
 '979\n',
 '980\n',
 '981\n',
 '982\n',
 '983\n',
 '984\n',
 '985\n',
 '986\n',
 '987\n',
 '988\n',
 '989\n',
 '990\n',
 '991\n',
 '992\n',
 '993\n',
 '994\n',
 '995\n',
 '996\n',
 '997\n',
 '998\n',
 '999\n',
 'AA107\n',
 ...]

In [132]:
for i in range(len(names)):
    names[i]=names[i].rstrip()

In [133]:
df=df[df.columns[:-1]]

In [134]:
df.columns=names

In [135]:
df.index=names

In [136]:
df

,1,10,100,101,102,103,104,105,106,107,...,998,999,AA107,AA108,AA109,AA110,AA111,AA112,AA113,AA114
1,0.000000,0.002771,0.001243,0.002484,0.002442,0.002615,0.002565,0.002742,0.002679,0.002748,...,0.006779,0.006755,0.009290,0.009281,0.009293,0.009296,0.009278,0.009315,0.009362,0.009303
10,0.002771,0.000000,0.002790,0.002807,0.002885,0.002764,0.002804,0.002742,0.002500,0.002580,...,0.006743,0.006716,0.009186,0.009172,0.009210,0.009179,0.009174,0.009210,0.009244,0.009199
100,0.001243,0.002790,0.000000,0.002480,0.002414,0.002699,0.002631,0.002786,0.002701,0.002773,...,0.006771,0.006745,0.009285,0.009273,0.009297,0.009286,0.009263,0.009302,0.009347,0.009290
101,0.002484,0.002807,0.002480,0.000000,0.002537,0.002830,0.002548,0.002957,0.002733,0.002782,...,0.006705,0.006679,0.009311,0.009308,0.009309,0.009296,0.009290,0.009333,0.009384,0.009311
102,0.002442,0.002885,0.002414,0.002537,0.000000,0.002852,0.002626,0.002941,0.002811,0.002920,...,0.006724,0.006693,0.009262,0.009254,0.009264,0.009254,0.009245,0.009279,0.009332,0.009264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
AA110,0.009296,0.009179,0.009286,0.009296,0.009254,0.009305,0.009214,0.009351,0.009274,0.009286,...,0.012301,0.012283,0.005794,0.006460,0.006332,0.000000,0.006482,0.006644,0.006726,0.006663
AA111,0.009278,0.009174,0.009263,0.009290,0.009245,0.009289,0.009219,0.009335,0.009266,0.009283,...,0.012348,0.012329,0.006205,0.006469,0.006604,0.006482,0.000000,0.006491,0.006470,0.006609
AA112,0.009315,0.009210,0.009302,0.009333,0.009279,0.009334,0.009256,0.009369,0.009301,0.009318,...,0.012347,0.012329,0.006763,0.006764,0.006565,0.006644,0.006491,0.000000,0.006625,0.006649
AA113,0.009362,0.009244,0.009347,0.009384,0.009332,0.009384,0.009292,0.009429,0.009351,0.009377,...,0.012419,0.012399,0.006539,0.006674,0.006581,0.006726,0.006470,0.006625,0.000000,0.006702
AA114,0.009303,0.009199,0.009290,0.009311,0.009264,0.009324,0.009254,0.009363,0.009293,0.009320,...,0.012341,0.012320,0.006809,0.006741,0.006416,0.006663,0.006609,0.006649,0.006702,0.000000

In [137]:
pop

['1',
 '97',
 '35',
 '62',
 '44',
 '43',
 '98',
 '65',
 '51',
 '99',
 '100',
 '101',
 '77',
 '26',
 '25',
 '102',
 '123',
 '136',
 '133',
 '137',
 '734',
 '138',
 '139',
 '125',
 '105',
 '103',
 '135',
 '104',
 '2',
 '106',
 '21',
 '81',
 '27',
 '89',
 '90',
 '53',
 '141',
 '47',
 '56',
 '55',
 '126',
 '45',
 '3',
 '67B',
 '54',
 '142',
 '72',
 '28',
 '143',
 '52',
 '31',
 '68',
 '66',
 '69',
 '144',
 '107',
 '11',
 '85',
 '108',
 '887',
 '888',
 '889',
 '145',
 '146',
 '147',
 '140',
 '80',
 '39',
 '78',
 '86',
 '29',
 '92',
 '60',
 '59',
 '76',
 '94',
 '18',
 '30',
 '4',
 '46',
 '49',
 '48',
 '32',
 '38',
 '83',
 '109',
 '14',
 '127',
 '110',
 '42',
 '74',
 '15',
 '16',
 '57',
 '148',
 '71',
 '96',
 '87',
 '50',
 '149',
 '91',
 '890',
 '891',
 '892',
 '128',
 '893',
 '894',
 '150',
 '151',
 '152',
 '129',
 '153',
 '131',
 '132',
 '73',
 '112',
 '20',
 '9',
 '17',
 '82',
 '23',
 '117',
 '84',
 '111',
 '113',
 '114',
 '115',
 '116',
 '19',
 '70',
 '61',
 '5',
 '95',
 '22',
 '118',
 '171',
 '170',
 '34',
 '119',
 '120',
 '6',
 '75',
 '36',
 '169',
 '79',
 '168',
 '63',
 '121',
 '895',
 '896',
 '897',
 '898',
 '167',
 '899',
 '900',
 '901',
 '902',
 '164',
 '163',
 '162',
 '178',
 '177',
 '176',
 '175',
 '174',
 '727',
 '173',
 '726',
 '725',
 '728',
 '179',
 '134',
 '88',
 '41',
 '7',
 '10',
 '181',
 '122',
 '33',
 '40',
 '64',
 '13',
 '12',
 '58',
 '37B',
 '8',
 '93',
 '24',
 '903',
 '904',
 '905',
 '906',
 '907',
 '8522106001051',
 '8522106001053',
 '8522106001055',
 '8522106001058',
 '8522106001060',
 '683',
 '684',
 '685',
 '686',
 '688',
 '689',
 '690',
 '803',
 '804',
 '805',
 '806',
 '807',
 '808']

In [138]:
a=df.loc[pop]

In [139]:
a=a[pop]

In [140]:
a

,1,97,35,62,44,43,98,65,51,99,...,686,688,689,690,803,804,805,806,807,808
1,0.000000,0.000166,0.000408,0.000095,0.000296,0.001054,0.000453,0.000422,0.000817,0.001244,...,0.003781,0.003963,0.003996,0.003966,0.003981,0.003919,0.003952,0.003959,0.004005,0.003996
97,0.000166,0.000000,0.000405,0.000111,0.000290,0.001056,0.000508,0.000463,0.000852,0.001264,...,0.003790,0.003965,0.004000,0.003969,0.003989,0.003924,0.003958,0.003963,0.004009,0.003998
35,0.000408,0.000405,0.000000,0.000378,0.000314,0.001186,0.000713,0.000657,0.001039,0.001373,...,0.003778,0.003983,0.004015,0.003980,0.003999,0.003944,0.003960,0.003979,0.004023,0.004013
62,0.000095,0.000111,0.000378,0.000000,0.000259,0.001040,0.000439,0.000402,0.000796,0.001263,...,0.003788,0.003966,0.003999,0.003968,0.003988,0.003921,0.003954,0.003962,0.004008,0.003997
44,0.000296,0.000290,0.000314,0.000259,0.000000,0.001172,0.000596,0.000568,0.000957,0.001347,...,0.003789,0.003969,0.004005,0.003971,0.003989,0.003932,0.003956,0.003965,0.004012,0.004001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
804,0.003919,0.003924,0.003944,0.003921,0.003932,0.003961,0.003926,0.003932,0.003943,0.003977,...,0.003054,0.001283,0.001211,0.001238,0.001515,0.000000,0.001263,0.001376,0.001323,0.001249
805,0.003952,0.003958,0.003960,0.003954,0.003956,0.003935,0.003939,0.003942,0.003943,0.003988,...,0.003036,0.001678,0.001530,0.001304,0.001455,0.001263,0.000000,0.001473,0.001640,0.001505
806,0.003959,0.003963,0.003979,0.003962,0.003965,0.003974,0.003964,0.003961,0.003974,0.004005,...,0.003045,0.001087,0.001030,0.001341,0.001286,0.001376,0.001473,0.000000,0.001205,0.001153
807,0.004005,0.004009,0.004023,0.004008,0.004012,0.004003,0.003999,0.004009,0.004005,0.004039,...,0.003074,0.001221,0.000999,0.001337,0.001279,0.001323,0.001640,0.001205,0.000000,0.001166
808,0.003996,0.003998,0.004013,0.003997,0.004001,0.004010,0.004001,0.003996,0.003995,0.004018,...,0.003042,0.001224,0.000865,0.001359,0.001044,0.001249,0.001505,0.001153,0.001166,0.000000

In [141]:
a.to_csv("genetic_distances_square_ind_pi_comp.tsv",sep="\t")

In [2]:
import pandas as pd

In [4]:
geo=pd.read_csv("harvesine_distances_ind_comp.tsv", sep="\t")

In [5]:
genetic=pd.read_csv("genetic_distances_ind_comp.tsv", sep="\t")

FileNotFoundError: [Errno 2] No such file or directory: 'genetic_distances_ind_comp.tsv'