In [2]:
import pandas as pd

In [3]:
a='''ATGACGGCGACTGAAACAATCGCCGCCGCGATAAACCAAATCGACGAGAA
GAAAGAGAAGCTGAAGAAAGCTTTCGACGATCTTCAATCACACCGTTCTC
TCCTCTCACCGTCTTTCTCACTTTCATGGTCTGAGATCGACTCTCACTTC
TCCTCTCTCCAATCCTCTCTCTCTAACCGTTTCCGTCTCCTCCAATCCGC
ATCTCAATTAGAACATGATCCACACAGAATCGAATCCGCCGATGCAAAGA
CGTCGCCGGAGGAGGAGGAGACAACGACGGTTGTTGAACCGGAATTGAGA
ACGTTGTGTGAGAAGATGGACGGAATTGGATTGTGTAAGTATTTGATTGA
TCGTTGGGATGATGATTCGCCACTCAATCTAGAACTATCTGCAGCGATTC
GGTACTCTACAGATCCAGCTTCAATGGTGTTAGACGCAATCCAAGGTTCG
TATCACCAAACTCAATCATCGAGAAAATCAGTTGATGTTAGGAGAGTTTT
CGTTTTGTTAATGGAAGCTTTGATTGAGAACAATGGTGAAATCAAAGTTG
ATGTTAGAGATAGAGCTAAGAGACTTGGTTACGATTGGAAAACGAAGATA
GGTGTTAAGCCTTTTGAGGCGTTACTGTTTCTGCATTTGGTTGCAGCTTT
TGAATTAGGATCTGAGTTTAGCTCTGAGGAGATTTCGGATTACGTTTTCA
TGATTGGTAAGTATAAGCAAGCGACTTCGGTGTGTAACAAGATTGGTTTA
GATAGTGAAAGTGTTGGAAATTTGATCAAGAAGCTCTTGGATTCTGGTAA
GGCAGTCTTGGCAGTTAAGTTTATGTATGAGTGTGGAGTGATTGATGGAT
TTGAACCAATCACTACTTTGAAATCTTACGTTAAGGAGTTGAGAGTAGCT
GCTTATAGAATCTGTGTGGAAGGTAACTACTCGCTTAAGTCGCAGAACGA
AGCTACTGATAAAGAAGTCAGTGCTTTGAAAGCAGTGATCAAGATTGTCA
AAGATCACACTCTTGAGTCTGAGTTTTGTGATGAGAAACTGGAGCAACGT
GTAGATGAGCTGGAGAAACAAAAGGCGTTGAGGAAACGCAACACCGCTAA
CGCTAATCCTAATCCTCAGCAAGAACCACAGCATAAAGGGAGAAAGCGAG
CTCGAGGTGGAAATGGTACACAAGTTCCAGCTCCTTTGAGTCAGCAACAG
CCGCTTCCGAGATCAGAAGCTGTTCTTATGCCTGGCTTACAGTTAAACCC
CTTTGGTCTTGTGAACTCAGCACTTGGTGGTGGTGTTGTTCCTTACATGA
ACCCATTAGCTGGGCTCTATGGTTCTGCAGCAGCTCCTCAATCTGTTTAC
TATGGTCAACAAAATCGATTTGTGTTGCCGGGTCAATATCATCCACCTTA
TTATTCTCAG'''

In [4]:
len("".join(a.split()))

1410

In [5]:
a="".join(a.split())

In [7]:
mutations_index=[880,898,1010,1016,1045,1366]

In [8]:
mutations=[]
for i in mutations_index:
    mutations.append(a[i-1])

In [7]:
mutation_dict={}

In [8]:
mutation_dict["a_alpina_ref"]=mutations

In [9]:
mutation_dict["a_alpina_france"]=["A","T","A","C","G","G"]

In [10]:
mutation_dict["a_alpina_ref"]

['G', 'G', 'C', 'A', 'C', 'C']

In [9]:
mont_file=open("N:/dep_coupland/grp_fulgione/mehak/data/spanish_project/FRL1_arabis_genus/amont_2G2WJ14M014-Alignment.xml")

In [13]:
mont_file=mont_file.readlines()

In [21]:
a_mont_q=mont_file[49].split("<Hsp_qseq>")[1].split("</Hsp_qseq>")[0]

In [23]:
len(a_mont_q)

1410

In [30]:
a_mont=mont_file[50].split("<Hsp_hseq>")[1].split("</Hsp_hseq>")[0]

In [4]:
def give_mutations(a):
    a="".join(a.split())
    mutations_index=[880,898,1010,1016,1045,1366]
    mutations=[]
    for i in mutations_index:
        mutations.append(a[i-1])
    return mutations

In [32]:
len("".join(a_mont.split()))

1410

In [33]:
mutation_dict["a_mont"]=give_mutations(a_mont)

In [34]:
mutation_dict["a_mont"]

['A', 'T', 'A', 'C', 'G', 'G']

In [29]:
##query also has spaces in alignment

In [36]:
file=open("N:/dep_coupland/grp_fulgione/mehak/data/spanish_project/FRL1_arabis_genus/a_sag_2G2Z4YPJ016-Alignment.xml")

In [37]:
file=file.readlines()
a_sag_q=file[49].split("<Hsp_qseq>")[1].split("</Hsp_qseq>")[0]
a_sag=file[50].split("<Hsp_hseq>")[1].split("</Hsp_hseq>")[0]

In [40]:
print(len("".join(a_sag.split())))
print(len("".join(a_sag_q.split())))

1413
1413

In [41]:
for i , c in enumerate(a_sag_q):
    if c=="-":
        print(i)

555
556
557

In [42]:
a_sag=a_sag[:555]+a_sag[558:]

In [43]:
len("".join(a_sag.split()))

1410

In [45]:
give_mutations(a_sag)

['A', 'G', 'A', 'A', 'G', 'G']

In [90]:
mutation_dict["a_sag"]=give_mutations(a_sag)

In [48]:
file=open("N:/dep_coupland/grp_fulgione/mehak/data/spanish_project/FRL1_arabis_genus/a_nem_2G3U69B1016-Alignment.xml")

In [49]:
file=file.readlines()
a_nem_q=file[49].split("<Hsp_qseq>")[1].split("</Hsp_qseq>")[0]
a_nem=file[50].split("<Hsp_hseq>")[1].split("</Hsp_hseq>")[0]

In [50]:
print(len("".join(a_nem.split())))
print(len("".join(a_nem_q.split())))

1413
1413

In [51]:
##query also has spaces

In [52]:
for i , c in enumerate(a_nem_q):
    if c=="-":
        print(i)

555
556
557

In [53]:
a_nem=a_nem[:555]+a_nem[558:]

In [54]:
len("".join(a_nem.split()))

1410

In [55]:
give_mutations(a_nem)

['A', 'G', 'A', 'A', 'G', 'G']

In [56]:
mutation_dict["a_nem"]=give_mutations(a_nem)

In [57]:
file=open("N:/dep_coupland/grp_fulgione/mehak/data/spanish_project/FRL1_arabis_genus/a_nord_2G6FSUEW014-Alignment.xml")

In [58]:
file=file.readlines()
a_nord_q=file[49].split("<Hsp_qseq>")[1].split("</Hsp_qseq>")[0]
a_nord=file[50].split("<Hsp_hseq>")[1].split("</Hsp_hseq>")[0]

In [59]:
print(len("".join(a_nord.split())))
print(len("".join(a_nord_q.split())))

1416
1416

In [60]:
for i , c in enumerate(a_nord_q):
    if c=="-":
        print(i)

558
559
560
561
562
563

In [61]:
a_nord=a_nord[:558]+a_nord[564:]

In [62]:
len("".join(a_nord.split()))

1410

In [63]:
give_mutations(a_nord)

['A', 'G', 'A', 'A', 'G', 'G']

In [64]:
mutation_dict["a_nord"]=give_mutations(a_nord)

In [65]:
file=open("N:/dep_coupland/grp_fulgione/mehak/data/spanish_project/FRL1_arabis_genus/a_hir_2G4RFHGN016-Alignment.xml")

In [66]:
file=file.readlines()
a_hir_q=file[49].split("<Hsp_qseq>")[1].split("</Hsp_qseq>")[0]
a_hir=file[50].split("<Hsp_hseq>")[1].split("</Hsp_hseq>")[0]

In [68]:
print(len("".join(a_hir.split())))
print(len("".join(a_hir_q.split())))

1413
1413

In [69]:
for i , c in enumerate(a_hir_q):
    if c=="-":
        print(i)

555
556
557

In [70]:
a_hir=a_hir[:555]+a_hir[558:]

In [71]:
len("".join(a_hir.split()))

1410

In [72]:
give_mutations(a_hir)

['A', 'G', 'A', 'A', 'G', 'G']

In [73]:
mutation_dict["a_hir"]=give_mutations(a_hir)

In [74]:
file=open("N:/dep_coupland/grp_fulgione/mehak/data/spanish_project/FRL1_arabis_genus/a_cil_2G6JVD16014-Alignment.xml")

In [75]:
file=file.readlines()
a_cil_q=file[49].split("<Hsp_qseq>")[1].split("</Hsp_qseq>")[0]
a_cil=file[50].split("<Hsp_hseq>")[1].split("</Hsp_hseq>")[0]

In [76]:
print(len("".join(a_cil.split())))
print(len("".join(a_cil_q.split())))

1413
1413

In [77]:
for i , c in enumerate(a_cil_q):
    if c=="-":
        print(i)

555
556
557

In [78]:
a_cil=a_cil[:555]+a_cil[558:]

In [79]:
give_mutations(a_cil)

['A', 'G', 'A', 'A', 'G', 'G']

In [80]:
mutation_dict["a_cil"]=give_mutations(a_cil)

In [84]:
file=open("N:/dep_coupland/grp_fulgione/mehak/data/spanish_project/FRL1_arabis_genus/a_cae_2G7KP8BF014-Alignment.xml")

In [85]:
file=file.readlines()
a_cae_q=file[49].split("<Hsp_qseq>")[1].split("</Hsp_qseq>")[0]
a_cae=file[50].split("<Hsp_hseq>")[1].split("</Hsp_hseq>")[0]

In [86]:
print(len("".join(a_cae.split())))
print(len("".join(a_cae_q.split())))

1410
1410

In [87]:
give_mutations(a_cae)

['A', 'G', 'A', 'A', 'G', 'G']

In [88]:
mutation_dict["a_cae"]=give_mutations(a_cae)

In [82]:
pd.DataFrame(mutation_dict)

  a_alpina_ref a_alpina_france a_mont a_sag a_nem a_nord a_hir a_cil a_cae
0            G               A      A     A     A      A     A     A     A
1            G               T      T     G     G      G     G     G     G
2            C               A      A     A     A      A     A     A     A
3            A               C      C     A     A      A     A     A     A
4            C               G      G     G     G      G     G     G     G
5            C               G      G     G     G      G     G     G     G

In [92]:
df=pd.DataFrame(mutation_dict)

In [93]:
df.index=mutations_index

In [94]:
df

     a_alpina_ref a_alpina_france a_mont a_nem a_nord a_hir a_cil a_cae a_sag
880             G               A      A     A      A     A     A     A     A
898             G               T      T     G      G     G     G     G     G
1010            C               A      A     A      A     A     A     A     A
1016            A               C      C     A      A     A     A     A     A
1045            C               G      G     G      G     G     G     G     G
1366            C               G      G     G      G     G     G     G     G

In [5]:
file=open("N:/dep_coupland/grp_fulgione/mehak/data/spanish_project/FRL1_arabis_genus/a_thaliana_2N157AXG016-Alignment.xml")

In [6]:
file=file.readlines()
a_tha_q=file[49].split("<Hsp_qseq>")[1].split("</Hsp_qseq>")[0]
a_tha=file[50].split("<Hsp_hseq>")[1].split("</Hsp_hseq>")[0]

In [7]:
print(len("".join(a_tha.split())))
print(len("".join(a_tha_q.split())))

1439
1439

In [9]:
for i , c in enumerate(a_tha_q):
    if c=="-":
        print(i)

250
251
252
253
254
255
272
273
274
357
358
1167
1168
1169
1246
1247
1248
1249
1250
1251
1252
1253
1254
1255
1256
1257
1258
1259
1260

In [10]:
a_tha=a_tha[:250]+a_tha[256:272]+a_tha[275:357]+a_tha[359:1167]+a_tha[1170:1246]+a_tha[1261:]

In [12]:
print(len("".join(a_tha.split())))

1410

In [13]:
give_mutations(a_tha)

['A', 'G', 'A', 'A', 'G', 'G']